/**
 * Generated by Farm.js. Do not edit.
 * Contains project-specific route, environment, and internationalization types.
 */

import "@farm.js/core/image";

/**
 * Auto-generated route types from src/app.
 * Link href and route component props are typed automatically from generated declarations.
 * Regenerated on dev start and when routes change.
 * Set suppressLintOnLink: true in farm.config.ts to accept any string on Link href.
 */
export type RoutePath =
  | "/"
  | "/docs"
  | `/docs/${string}`;
export type RoutePattern =
  | "/"
  | "/docs"
  | "/docs/[...docs]";
export type RouteModulePattern =
  | "/"
  | "/docs"
  | "/docs/[...docs]";
declare module "@farm.js/core/client" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

declare module "@farm.js/core" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
  // Ensure root import ("@farm.js/core") uses the same typed Link signature as client entry.
  const Link: typeof import("@farm.js/core/client").Link;
}

// Internal declaration path used by @farm.js/core root type re-exports.
declare module "@farm.js/core/dist/client.js" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

declare global {
  namespace FarmJS {
    interface RouteRegistry {
      pattern: import("./farm").RouteModulePattern;
    }
  }
}

/**
 * Auto-generated env types from farm.config.
 * Regenerated on dev start, build, and farm generate.
 */
import type FarmConfig from "../farm.config";
import type { InferEnv } from "@farm.js/core/env";

type FarmConfigEnv = typeof FarmConfig extends { env?: infer TEnv } ? NonNullable<TEnv> : never;
type FarmResolvedEnv = [FarmConfigEnv] extends [never]
  ? { server: {}; public: {} }
  : InferEnv<FarmConfigEnv>;

declare module "@farm.js/core/env" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

declare module "@farm.js/core" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

export {};
